name: 'SWM Github Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'
jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

      steps:
      - name: Say Hello World 1
        shell: bash
        run: |
          echo "Hello World"

  deploy-dev:
    name: 'Deploy to dev'

    runs-on: 'ubuntu-latest'

      steps:
      - name: Say Hello World 1
        shell: bash
        run: |
          echo "Hello World"

  deploy-staging:
    name: 'Deploy to staging'

    runs-on: 'ubuntu-latest'

      steps:
      - name: Say Hello World 1
        shell: bash
        run: |
          echo "Hello World"

  deploy-staging2:
    name: 'Deploy to staging2'

    runs-on: 'ubuntu-latest'

      steps:
      - name: Say Hello World 1
        shell: bash
        run: |
          echo "Hello World"

  deploy-staging3:
    name: 'Deploy to staging3'

    runs-on: 'ubuntu-latest'

      steps:
      - name: Say Hello World 1
        shell: bash
        run: |
          echo "Hello World"
  