name: 'SWM Github Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'
jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'

    steps:
    - name: Say Hello World 1
      shell: bash
      run: |
        echo "Hello World from step 1"

        randomValue="swm$(echo $RANDOM)"

        echo "STEP_VALUE=$randomValue" >> $GITHUB_ENV
    
    - name: Say Hello World 2
      shell: pwsh
      run: |
        echo "Hello World from step 2"

        echo "STEP_VALUE: ${{ env.STEP_VALUE }}"

