name: 'SWM Github Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'
jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Send a message to Webex Space
      shell: bash
      run: |
        curl --location --request POST https://webexapis.com/v1/messages \
          --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
          --header 'Content-type: application/json' \
          --data-raw '{
            "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
            "text": "Second Message from GHA, hyeongrae "
          }'