name: 'SWM Github Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'
jobs:
  build-test:
    name: 'Build & Test'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Send a message to Webex Space
      shell: bash
      run: |
        curl -X POST https://webexapis.com/v1/messages \
          -H "Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}" \
          -H "Content-type: applicatino/json" \
          -d "{
            "roomid": "${{ secrets.WEBEX_ROOM_ID }}",
            "text": "Message from GHA, hyeongrae"
          }"