name: 'SWM Github Actions Basic'

on: push

env:
  GLOBAL_LEVEL: 'GLOBAL VALUE'
jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        node js: [ '16', '18' ]

    runs-on: ${{ matrix.os }}

    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'

    steps:
    - name: Say Hello World 1 - ${{ matrix.os }}
      id: helloworld1
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "nodejs version: ${{ matrix.nodejs }}"
    
    - name: Say Hello World 2 - ${{ matrix.os }}
      if: matrix.os == 'windows-latest' && matrix.nodejs == 16
      id: helloworld2
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "nodejs version: ${{ matrix.nodejs }}"

